version: '{build}'
skip_tags: true
clone_depth: 30
build: off

platform:
  - x86
  - x64

environment:
  matrix:
    - platform: x86
      JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    - platform: x86
      JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - platform: x64
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven\apache-maven-3.3.3" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.3\bin;%JAVA_HOME%\bin;%PATH%

#build_script:
#  - echo no build
#
test_script:
  - mvn clean verify

cache:
  - C:\maven\apache-maven-3.3.3